// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/psychologist/slots": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all slots for the logged-in psychologist, including student details for booked slots.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "psychologist-slots"
                ],
                "summary": "Get psychologist's own schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PsychologistScheduleResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Psychologist generates multiple slots based on a weekly schedule pattern between start_date and end_date.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "psychologist-slots"
                ],
                "summary": "Create schedule slots for a psychologist",
                "parameters": [
                    {
                        "description": "Schedule configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateScheduleInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ScheduleCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "validation error or no slots created",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "only psychologists can create slots",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "database error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/psychologist/slots/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows a psychologist to remove an available slot from their schedule. Fails if the slot is already booked.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "psychologist-slots"
                ],
                "summary": "Delete an unbooked slot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slot ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not authorized or not the owner",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Slot not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Cannot delete a booked slot",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/psychologist/slots/{id}/notes": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Psychologist writes private notes after a session. Hidden from the student.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "psychologist-slots"
                ],
                "summary": "Add private notes to a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "The private notes",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddNoteInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    }
                }
            }
        },
        "/psychologist/students/{student_id}/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Psychologist views all past sessions and private notes for a specific student.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "psychologist-slots"
                ],
                "summary": "Get a student's session history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StudentHistoryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/slots": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns free slots for a given psychologist and date, enriched with psychologist name via gRPC.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slots"
                ],
                "summary": "Get available slots for a specific date",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Psychologist ID",
                        "name": "psychologist_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date in format YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SlotResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "missing params",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "database or gRPC error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/slots/calendar": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns dates within the specified month where the psychologist has at least one free slot.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slots"
                ],
                "summary": "Get calendar days with available slots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Psychologist ID",
                        "name": "psychologist_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Year (e.g. 2026)",
                        "name": "year",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Month (1-12 or 01-12)",
                        "name": "month",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CalendarAvailabilityResponse"
                        }
                    },
                    "400": {
                        "description": "missing params",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student/appointments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of all upcoming and past appointments booked by the logged-in student.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-booking"
                ],
                "summary": "Get student's booked appointments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StudentAppointmentResponse"
                            }
                        }
                    },
                    "403": {
                        "description": "Not authorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student/slots/{id}/book": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Student books a specific slot. Uses optimistic locking on the version field to avoid double-booking.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-booking"
                ],
                "summary": "Book a slot as a student",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Booking details: type and answers",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BookSlotInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "slot not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "slot already booked or just booked",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "database error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student/slots/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Student cancels their own booking. This frees up the slot for other students to book.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-booking"
                ],
                "summary": "Cancel a booked appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slot ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not authorized or not the owner",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Slot not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Slot is not booked",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/student/slots/{id}/reschedule": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Student moves their booking from one slot to another available slot. This is done atomically so they don't lose their original slot if the new one is taken.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student-booking"
                ],
                "summary": "Reschedule an appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Old Slot ID (The one currently booked)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "The new Slot ID to move to",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RescheduleInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not authorized or not the owner",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Slot not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "New slot already booked or race condition",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddNoteInput": {
            "type": "object",
            "required": [
                "notes"
            ],
            "properties": {
                "notes": {
                    "type": "string"
                }
            }
        },
        "models.BookSlotInput": {
            "type": "object",
            "required": [
                "booking_type"
            ],
            "properties": {
                "answers": {
                    "type": "string"
                },
                "booking_type": {
                    "type": "string",
                    "enum": [
                        "online",
                        "offline"
                    ]
                }
            }
        },
        "models.CalendarAvailabilityResponse": {
            "type": "object",
            "properties": {
                "available_dates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2026-02-10",
                        "2026-02-14"
                    ]
                }
            }
        },
        "models.CreateScheduleInput": {
            "type": "object",
            "required": [
                "end_date",
                "schedule",
                "start_date"
            ],
            "properties": {
                "duration": {
                    "description": "50 (default)",
                    "type": "integer"
                },
                "end_date": {
                    "description": "\"2026-03-20\"",
                    "type": "string"
                },
                "schedule": {
                    "description": "The template",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DaySchedule"
                    }
                },
                "start_date": {
                    "description": "\"2026-02-20\"",
                    "type": "string"
                }
            }
        },
        "models.DaySchedule": {
            "type": "object",
            "required": [
                "day_of_week",
                "start_times"
            ],
            "properties": {
                "day_of_week": {
                    "description": "1=Mon, 2=Tue...",
                    "type": "integer"
                },
                "start_times": {
                    "description": "[\"09:00\", \"10:00\", \"14:00\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid start_date"
                }
            }
        },
        "models.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Booking successful"
                }
            }
        },
        "models.PsychologistScheduleResponse": {
            "type": "object",
            "properties": {
                "booking_type": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_booked": {
                    "type": "boolean"
                },
                "psychologist_id": {
                    "type": "string"
                },
                "psychologist_name": {
                    "type": "string"
                },
                "questionnaire_answers": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "student_name": {
                    "type": "string"
                }
            }
        },
        "models.RescheduleInput": {
            "type": "object",
            "required": [
                "new_slot_id"
            ],
            "properties": {
                "new_slot_id": {
                    "type": "string"
                }
            }
        },
        "models.ScheduleCreatedResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 24
                },
                "message": {
                    "type": "string",
                    "example": "Schedule created successfully"
                }
            }
        },
        "models.SlotResponse": {
            "type": "object",
            "properties": {
                "booking_type": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_booked": {
                    "type": "boolean"
                },
                "psychologist_id": {
                    "type": "string"
                },
                "psychologist_name": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "models.StudentAppointmentResponse": {
            "type": "object",
            "properties": {
                "booking_type": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "psychologist_id": {
                    "type": "string"
                },
                "psychologist_name": {
                    "type": "string"
                },
                "questionnaire_answers": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "models.StudentHistoryResponse": {
            "type": "object",
            "properties": {
                "booking_type": {
                    "type": "string"
                },
                "psychologist_notes": {
                    "type": "string"
                },
                "questionnaire_answers": {
                    "type": "string"
                },
                "slot_id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "KBTU Psychologist Booking Service API",
	Description:      "Slot scheduling and booking system for KBTU counseling platform.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
