// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/bookings/booking.proto

package bookings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMeetingLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	MeetingLink   string                 `protobuf:"bytes,2,opt,name=meeting_link,json=meetingLink,proto3" json:"meeting_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeetingLinkRequest) Reset() {
	*x = UpdateMeetingLinkRequest{}
	mi := &file_proto_bookings_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingLinkRequest) ProtoMessage() {}

func (x *UpdateMeetingLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookings_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeetingLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_bookings_booking_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMeetingLinkRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *UpdateMeetingLinkRequest) GetMeetingLink() string {
	if x != nil {
		return x.MeetingLink
	}
	return ""
}

type UpdateMeetingLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeetingLinkResponse) Reset() {
	*x = UpdateMeetingLinkResponse{}
	mi := &file_proto_bookings_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingLinkResponse) ProtoMessage() {}

func (x *UpdateMeetingLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookings_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingLinkResponse.ProtoReflect.Descriptor instead.
func (*UpdateMeetingLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_bookings_booking_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMeetingLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_bookings_booking_proto protoreflect.FileDescriptor

const file_proto_bookings_booking_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/bookings/booking.proto\x12\bbookings\"V\n" +
	"\x18UpdateMeetingLinkRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12!\n" +
	"\fmeeting_link\x18\x02 \x01(\tR\vmeetingLink\"5\n" +
	"\x19UpdateMeetingLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2n\n" +
	"\x0eBookingService\x12\\\n" +
	"\x11UpdateMeetingLink\x12\".bookings.UpdateMeetingLinkRequest\x1a#.bookings.UpdateMeetingLinkResponseBAZ?github.com/pokonti/psychologist-backend/proto/bookings;bookingsb\x06proto3"

var (
	file_proto_bookings_booking_proto_rawDescOnce sync.Once
	file_proto_bookings_booking_proto_rawDescData []byte
)

func file_proto_bookings_booking_proto_rawDescGZIP() []byte {
	file_proto_bookings_booking_proto_rawDescOnce.Do(func() {
		file_proto_bookings_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bookings_booking_proto_rawDesc), len(file_proto_bookings_booking_proto_rawDesc)))
	})
	return file_proto_bookings_booking_proto_rawDescData
}

var file_proto_bookings_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bookings_booking_proto_goTypes = []any{
	(*UpdateMeetingLinkRequest)(nil),  // 0: bookings.UpdateMeetingLinkRequest
	(*UpdateMeetingLinkResponse)(nil), // 1: bookings.UpdateMeetingLinkResponse
}
var file_proto_bookings_booking_proto_depIdxs = []int32{
	0, // 0: bookings.BookingService.UpdateMeetingLink:input_type -> bookings.UpdateMeetingLinkRequest
	1, // 1: bookings.BookingService.UpdateMeetingLink:output_type -> bookings.UpdateMeetingLinkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bookings_booking_proto_init() }
func file_proto_bookings_booking_proto_init() {
	if File_proto_bookings_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bookings_booking_proto_rawDesc), len(file_proto_bookings_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bookings_booking_proto_goTypes,
		DependencyIndexes: file_proto_bookings_booking_proto_depIdxs,
		MessageInfos:      file_proto_bookings_booking_proto_msgTypes,
	}.Build()
	File_proto_bookings_booking_proto = out.File
	file_proto_bookings_booking_proto_goTypes = nil
	file_proto_bookings_booking_proto_depIdxs = nil
}
