// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: userprofile/user_profile.proto

package userprofile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // user id from auth-service
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileRequest) Reset() {
	*x = CreateUserProfileRequest{}
	mi := &file_userprofile_user_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileRequest) ProtoMessage() {}

func (x *CreateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_user_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_userprofile_user_profile_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserProfileRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateUserProfileRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type CreateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileResponse) Reset() {
	*x = CreateUserProfileResponse{}
	mi := &file_userprofile_user_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileResponse) ProtoMessage() {}

func (x *CreateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_user_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_userprofile_user_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserProfileByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileByIDRequest) Reset() {
	*x = GetUserProfileByIDRequest{}
	mi := &file_userprofile_user_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileByIDRequest) ProtoMessage() {}

func (x *GetUserProfileByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_user_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileByIDRequest) Descriptor() ([]byte, []int) {
	return file_userprofile_user_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProfileByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserProfileByIDResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Gender         string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Specialization string                 `protobuf:"bytes,5,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Email          string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserProfileByIDResponse) Reset() {
	*x = GetUserProfileByIDResponse{}
	mi := &file_userprofile_user_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileByIDResponse) ProtoMessage() {}

func (x *GetUserProfileByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_user_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileByIDResponse) Descriptor() ([]byte, []int) {
	return file_userprofile_user_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileByIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

var File_userprofile_user_profile_proto protoreflect.FileDescriptor

const file_userprofile_user_profile_proto_rawDesc = "" +
	"\n" +
	"\x1euserprofile/user_profile.proto\x12\vuserprofile\"q\n" +
	"\x18CreateUserProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\"+\n" +
	"\x19CreateUserProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19GetUserProfileByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc9\x01\n" +
	"\x1aGetUserProfileByIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12&\n" +
	"\x0especialization\x18\x05 \x01(\tR\x0especialization\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone2\xdf\x01\n" +
	"\x12UserProfileService\x12b\n" +
	"\x11CreateUserProfile\x12%.userprofile.CreateUserProfileRequest\x1a&.userprofile.CreateUserProfileResponse\x12e\n" +
	"\x12GetUserProfileByID\x12&.userprofile.GetUserProfileByIDRequest\x1a'.userprofile.GetUserProfileByIDResponseBGZEgithub.com/pokonti/psychologist-backend/proto/userprofile;userprofileb\x06proto3"

var (
	file_userprofile_user_profile_proto_rawDescOnce sync.Once
	file_userprofile_user_profile_proto_rawDescData []byte
)

func file_userprofile_user_profile_proto_rawDescGZIP() []byte {
	file_userprofile_user_profile_proto_rawDescOnce.Do(func() {
		file_userprofile_user_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userprofile_user_profile_proto_rawDesc), len(file_userprofile_user_profile_proto_rawDesc)))
	})
	return file_userprofile_user_profile_proto_rawDescData
}

var file_userprofile_user_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_userprofile_user_profile_proto_goTypes = []any{
	(*CreateUserProfileRequest)(nil),   // 0: userprofile.CreateUserProfileRequest
	(*CreateUserProfileResponse)(nil),  // 1: userprofile.CreateUserProfileResponse
	(*GetUserProfileByIDRequest)(nil),  // 2: userprofile.GetUserProfileByIDRequest
	(*GetUserProfileByIDResponse)(nil), // 3: userprofile.GetUserProfileByIDResponse
}
var file_userprofile_user_profile_proto_depIdxs = []int32{
	0, // 0: userprofile.UserProfileService.CreateUserProfile:input_type -> userprofile.CreateUserProfileRequest
	2, // 1: userprofile.UserProfileService.GetUserProfileByID:input_type -> userprofile.GetUserProfileByIDRequest
	1, // 2: userprofile.UserProfileService.CreateUserProfile:output_type -> userprofile.CreateUserProfileResponse
	3, // 3: userprofile.UserProfileService.GetUserProfileByID:output_type -> userprofile.GetUserProfileByIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userprofile_user_profile_proto_init() }
func file_userprofile_user_profile_proto_init() {
	if File_userprofile_user_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userprofile_user_profile_proto_rawDesc), len(file_userprofile_user_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userprofile_user_profile_proto_goTypes,
		DependencyIndexes: file_userprofile_user_profile_proto_depIdxs,
		MessageInfos:      file_userprofile_user_profile_proto_msgTypes,
	}.Build()
	File_userprofile_user_profile_proto = out.File
	file_userprofile_user_profile_proto_goTypes = nil
	file_userprofile_user_profile_proto_depIdxs = nil
}
