// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/userprofile/user_profile.proto

package userprofile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // user id from auth-service
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileRequest) Reset() {
	*x = CreateUserProfileRequest{}
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileRequest) ProtoMessage() {}

func (x *CreateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_user_profile_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserProfileRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateUserProfileRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type CreateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileResponse) Reset() {
	*x = CreateUserProfileResponse{}
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileResponse) ProtoMessage() {}

func (x *CreateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_user_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserProfileByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileByIDRequest) Reset() {
	*x = GetUserProfileByIDRequest{}
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileByIDRequest) ProtoMessage() {}

func (x *GetUserProfileByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_user_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProfileByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserProfileByIDResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Gender         string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Specialization string                 `protobuf:"bytes,5,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Email          string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserProfileByIDResponse) Reset() {
	*x = GetUserProfileByIDResponse{}
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileByIDResponse) ProtoMessage() {}

func (x *GetUserProfileByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_user_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileByIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserProfileByIDResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// Request: List of UUIDs
type GetBatchUserProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchUserProfilesRequest) Reset() {
	*x = GetBatchUserProfilesRequest{}
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchUserProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchUserProfilesRequest) ProtoMessage() {}

func (x *GetBatchUserProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchUserProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetBatchUserProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_user_profile_proto_rawDescGZIP(), []int{4}
}

func (x *GetBatchUserProfilesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// A lighter user object for lists
type BasicUserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"` // Add photo_url here later if you have it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicUserProfile) Reset() {
	*x = BasicUserProfile{}
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicUserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicUserProfile) ProtoMessage() {}

func (x *BasicUserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicUserProfile.ProtoReflect.Descriptor instead.
func (*BasicUserProfile) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_user_profile_proto_rawDescGZIP(), []int{5}
}

func (x *BasicUserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BasicUserProfile) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type GetBatchUserProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*BasicUserProfile    `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchUserProfilesResponse) Reset() {
	*x = GetBatchUserProfilesResponse{}
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchUserProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchUserProfilesResponse) ProtoMessage() {}

func (x *GetBatchUserProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_user_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchUserProfilesResponse.ProtoReflect.Descriptor instead.
func (*GetBatchUserProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_user_profile_proto_rawDescGZIP(), []int{6}
}

func (x *GetBatchUserProfilesResponse) GetProfiles() []*BasicUserProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_proto_userprofile_user_profile_proto protoreflect.FileDescriptor

const file_proto_userprofile_user_profile_proto_rawDesc = "" +
	"\n" +
	"$proto/userprofile/user_profile.proto\x12\vuserprofile\"q\n" +
	"\x18CreateUserProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\"+\n" +
	"\x19CreateUserProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19GetUserProfileByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc9\x01\n" +
	"\x1aGetUserProfileByIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12&\n" +
	"\x0especialization\x18\x05 \x01(\tR\x0especialization\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\"/\n" +
	"\x1bGetBatchUserProfilesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"?\n" +
	"\x10BasicUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\"Y\n" +
	"\x1cGetBatchUserProfilesResponse\x129\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1d.userprofile.BasicUserProfileR\bprofiles2\xcc\x02\n" +
	"\x12UserProfileService\x12b\n" +
	"\x11CreateUserProfile\x12%.userprofile.CreateUserProfileRequest\x1a&.userprofile.CreateUserProfileResponse\x12e\n" +
	"\x12GetUserProfileByID\x12&.userprofile.GetUserProfileByIDRequest\x1a'.userprofile.GetUserProfileByIDResponse\x12k\n" +
	"\x14GetBatchUserProfiles\x12(.userprofile.GetBatchUserProfilesRequest\x1a).userprofile.GetBatchUserProfilesResponseBGZEgithub.com/pokonti/psychologist-backend/proto/userprofile;userprofileb\x06proto3"

var (
	file_proto_userprofile_user_profile_proto_rawDescOnce sync.Once
	file_proto_userprofile_user_profile_proto_rawDescData []byte
)

func file_proto_userprofile_user_profile_proto_rawDescGZIP() []byte {
	file_proto_userprofile_user_profile_proto_rawDescOnce.Do(func() {
		file_proto_userprofile_user_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userprofile_user_profile_proto_rawDesc), len(file_proto_userprofile_user_profile_proto_rawDesc)))
	})
	return file_proto_userprofile_user_profile_proto_rawDescData
}

var file_proto_userprofile_user_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_userprofile_user_profile_proto_goTypes = []any{
	(*CreateUserProfileRequest)(nil),     // 0: userprofile.CreateUserProfileRequest
	(*CreateUserProfileResponse)(nil),    // 1: userprofile.CreateUserProfileResponse
	(*GetUserProfileByIDRequest)(nil),    // 2: userprofile.GetUserProfileByIDRequest
	(*GetUserProfileByIDResponse)(nil),   // 3: userprofile.GetUserProfileByIDResponse
	(*GetBatchUserProfilesRequest)(nil),  // 4: userprofile.GetBatchUserProfilesRequest
	(*BasicUserProfile)(nil),             // 5: userprofile.BasicUserProfile
	(*GetBatchUserProfilesResponse)(nil), // 6: userprofile.GetBatchUserProfilesResponse
}
var file_proto_userprofile_user_profile_proto_depIdxs = []int32{
	5, // 0: userprofile.GetBatchUserProfilesResponse.profiles:type_name -> userprofile.BasicUserProfile
	0, // 1: userprofile.UserProfileService.CreateUserProfile:input_type -> userprofile.CreateUserProfileRequest
	2, // 2: userprofile.UserProfileService.GetUserProfileByID:input_type -> userprofile.GetUserProfileByIDRequest
	4, // 3: userprofile.UserProfileService.GetBatchUserProfiles:input_type -> userprofile.GetBatchUserProfilesRequest
	1, // 4: userprofile.UserProfileService.CreateUserProfile:output_type -> userprofile.CreateUserProfileResponse
	3, // 5: userprofile.UserProfileService.GetUserProfileByID:output_type -> userprofile.GetUserProfileByIDResponse
	6, // 6: userprofile.UserProfileService.GetBatchUserProfiles:output_type -> userprofile.GetBatchUserProfilesResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_userprofile_user_profile_proto_init() }
func file_proto_userprofile_user_profile_proto_init() {
	if File_proto_userprofile_user_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userprofile_user_profile_proto_rawDesc), len(file_proto_userprofile_user_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userprofile_user_profile_proto_goTypes,
		DependencyIndexes: file_proto_userprofile_user_profile_proto_depIdxs,
		MessageInfos:      file_proto_userprofile_user_profile_proto_msgTypes,
	}.Build()
	File_proto_userprofile_user_profile_proto = out.File
	file_proto_userprofile_user_profile_proto_goTypes = nil
	file_proto_userprofile_user_profile_proto_depIdxs = nil
}
